version: '3.7'

services:
  app-db:
    image: zkot2/postgresdb:v1
    container_name: db.postgres.dev
    ports:
      - "4532:5432"
    networks:
      - app-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 
         type: bind
         source: /home/zkot2/postgres/dbfiles
         target: /var/lib/postgresql/data
  
  data-readers:
    image: zkot2/file-reader.svc:v1
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    container_name: app.fsreader.dev
    volumes:
      - 
         type: bind
         source: /home/zkot2/app_data/fsreader/data
         target: /data
      - 
         type: bind
         source: /home/zkot2/app_data/fsreader/data/completed
         target: /data/completed           
      - 
         type: bind
         source: /home/zkot2/app_data/fsreader/data/bad
         target: /data/bad
      
    depends_on:
      - app-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: containers_network
